"""
tests/test_financial_advisor_integration.py
Live integration tests for the Shankh Financial Advisor and its sub-agents.
Runs end-to-end execution loops against live LLM providers and search endpoints.
"""

import os
import pytest

from shankh.agents.financial_advisor import FinancialAdvisor
from dotenv import load_dotenv
load_dotenv()  # Load environment variables from .env file
# Mark all tests in this module as live integration tests requiring active credentials
RUN_LIVE_AGENT_TESTS = os.getenv("RUN_LIVE_AGENT_TESTS") == "1"
HAS_REQUIRED_KEYS = all(
    os.getenv(k) for k in ["GOOGLE_API_KEY", "MISTRALAI_API_KEY", "CEREBRAS_API_KEY", "TAVILY_API_KEY"]
)

if not RUN_LIVE_AGENT_TESTS or not HAS_REQUIRED_KEYS:
    pytest.skip(
        "Skipping live integration tests. Set RUN_LIVE_AGENT_TESTS=1 and required API keys to enable.",
        allow_module_level=True,
    )


def _get_text_content(response) -> str:
    """
    Extracts plain text content from both structured block lists
    and standard raw string payloads for evaluation.
    """
    if isinstance(response, str):
        return response
    if isinstance(response, list):
        parts = []
        for part in response:
            if isinstance(part, dict) and "text" in part:
                parts.append(part["text"])
            elif isinstance(part, str):
                parts.append(part)
        return "".join(parts)
    if isinstance(response, dict):
        return response.get("text", str(response))
    return str(response)


def test_live_financial_advisor_market_snapshot():
    """
    Verifies that the orchestrator compiles correctly, evaluates the question,
    invokes the real market snapshot tool, and parses the returned mock metrics.
    """
    advisor = FinancialAdvisor()
    thread_id = "live-snapshot-test"
    
    question = (
        "Can you check the current market snapshot and tell me how the NIFTY 50 "
        "and India VIX are looking today?"
    )
    
    response = advisor.ask(question, thread_id=thread_id)
    
    print("\n--- [LIVE RUN] Market Snapshot Response ---")
    print(response)
    
    # Assert that the response container is of a valid type
    assert isinstance(response, (str, list, dict))
    
    text_content = _get_text_content(response)
    assert len(text_content) > 0
    
    # Verify the LLM correctly synthesized the output with returned data markers
    assert any(term in text_content.lower() for term in ["nifty", "vix", "snapshot"])


def test_live_financial_advisor_macro_delegation():
    """
    Verifies nested multi-agent delegation by forcing the orchestrator to call 
    the specialized Macro Analyst sub-agent tool, execute its internal tools, 
    and return the structured evaluation to the supervisor.
    """
    advisor = FinancialAdvisor()
    thread_id = "live-macro-test"
    
    question = (
        "Please consult your specialized macro analyst sub-agent to conduct "
        "a deep analysis of the current rate environment and institutional flow trends."
    )
    
    response = advisor.ask(question, thread_id=thread_id)
    
    print("\n--- [LIVE RUN] Macro Analyst Delegation Response ---")
    print(response)
    
    assert isinstance(response, (str, list, dict))
    
    text_content = _get_text_content(response)
    assert len(text_content) > 0
    
    # Verify that the final text contains structured components generated by the sub-agent
    assert any(term in text_content.lower() for term in ["regime", "rates", "flow", "assessment"])


def test_live_financial_advisor_web_search():
    """
    Verifies that the supervisor can trigger a live TavilySearch web query,
    retrieve raw internet content, and synthesize it into a readable research summary.
    """
    advisor = FinancialAdvisor()
    thread_id = "live-search-test"
    
    question = (
        "Search the web for any recent news or analyst commentary regarding "
        "the Indian central bank (RBI) monetary policy and summarize the top finding."
    )
    
    response = advisor.ask(question, thread_id=thread_id)
    
    print("\n--- [LIVE RUN] Tavily Search Response ---")
    print(response)
    
    assert isinstance(response, (str, list, dict))
    
    text_content = _get_text_content(response)
    assert len(text_content) > 0
