"""
Market Cycle Agent — Live Demo Dashboard.

A Streamlit app for demoing the Cycle Agent without needing the LLM layer: it calls
the deterministic tools directly (same as demo_cycle_agent.py) and lays out the live
classification, the evidence trail, the walk-forward backtest chart, and the honest
validation numbers (including the negative finding) in one screen.

Run:
    streamlit run scripts/cycle_dashboard.py

No API keys required to load — FMP_API_KEY / FRED_API_KEY unlock live valuation and
liquidity numbers if set; otherwise those sections show their FALLBACK_BENCHMARK /
insufficient_data labels honestly, same as the rest of this system.
"""

import json
import os
import sys
from pathlib import Path

import pandas as pd
import streamlit as st
from dotenv import load_dotenv

load_dotenv(Path(__file__).resolve().parents[1] / ".env")

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from shankh.agents.market.cycle_tools import get_market_cycle_synthesis  # noqa: E402

_OUTPUT_DIR = Path(__file__).resolve().parent / "output"

PHASE_COLORS = {
    "EXPANSION": "#2E7D32",
    "DISTRIBUTION": "#C77700",
    "CONTRACTION": "#C62828",
    "ACCUMULATION": "#1565C0",
}
RISK_COLORS = {"low": "#2E7D32", "medium": "#C77700", "high": "#C62828"}

st.set_page_config(page_title="Market Cycle Agent", page_icon="🔄", layout="wide")


@st.cache_data(ttl=300, show_spinner="Running synthesis (ZigZag / STC / trend / ERP / liquidity / earnings)...")
def fetch_synthesis() -> dict:
    raw = get_market_cycle_synthesis.invoke({})
    return json.loads(raw)


def render_header():
    st.title("Market Cycle Agent — Live Dashboard")
    st.caption(
        "Deterministic tool-layer output, called directly — no LLM in this view. "
        "This is the same JSON the LLM narration layer would receive and report verbatim."
    )
    col1, col2 = st.columns(2)
    with col1:
        fmp = "configured" if os.getenv("FMP_API_KEY") else "not set → FALLBACK_BENCHMARK"
        fred = "configured" if os.getenv("FRED_API_KEY") else "not set → insufficient_data"
        st.caption(f"FMP_API_KEY: **{fmp}**  |  FRED_API_KEY: **{fred}**  |  yfinance needs no key")
    with col2:
        if st.button("🔄 Refresh synthesis"):
            fetch_synthesis.clear()
            st.rerun()


def render_classification(data: dict):
    phase = data.get("cycle_phase", "N/A")
    confidence = data.get("cycle_confidence", 0.0)
    risk = data.get("transition_risk", "n/a")
    composite = data.get("composite_score", 0.0)

    c1, c2, c3, c4 = st.columns(4)
    c1.metric("Cycle Phase", phase)
    c2.metric("Confidence", f"{confidence:.0%}")
    c3.metric("Transition Risk", risk.upper())
    c4.metric("Composite Score", f"{composite:+.3f}")

    phase_color = PHASE_COLORS.get(phase, "#888")
    risk_color = RISK_COLORS.get(risk, "#888")
    st.markdown(
        f"""<div style="display:flex; gap:10px; margin-top:-8px; margin-bottom:16px;">
        <span style="background:{phase_color}20; color:{phase_color}; border:1px solid {phase_color};
        border-radius:6px; padding:2px 10px; font-size:13px; font-weight:600;">{phase}</span>
        <span style="background:{risk_color}20; color:{risk_color}; border:1px solid {risk_color};
        border-radius:6px; padding:2px 10px; font-size:13px; font-weight:600;">RISK: {risk.upper()}</span>
        </div>""",
        unsafe_allow_html=True,
    )

    watch = data.get("transition_watch", "none")
    if watch and watch != "none":
        st.info(f"Transition watch: **{watch}**")

    st.caption(f"As of: {data.get('as_of_date', 'n/a')}  |  Market: {data.get('market', 'NIFTY50')}")


def render_evidence(data: dict):
    st.subheader("Evidence Trail")
    evidence = data.get("evidence", [])
    if not evidence:
        st.warning("No evidence available.")
        return
    df = pd.DataFrame(evidence)
    df = df[["tier", "signal", "score", "reading", "note"]]
    df["score"] = df["score"].map(lambda s: f"{s:+.3f}")

    def _tier_badge(tier):
        colors = {"core": "#1565C0", "supporting": "#6A4C93", "contextual": "#888"}
        return f'<span style="color:{colors.get(tier, "#888")}; font-weight:600;">{tier.upper()}</span>'

    df_display = df.copy()
    df_display["tier"] = df_display["tier"].map(_tier_badge)
    st.write(df_display.to_html(escape=False, index=False), unsafe_allow_html=True)

    st.caption(f"Data freshness: {data.get('data_freshness', {})}")


def render_backtest():
    st.subheader("Walk-Forward Backtest (Core signals, 2018-2026 Nifty 50)")
    chart_path = _OUTPUT_DIR / "cycle_backtest_chart.png"
    if chart_path.exists():
        st.image(str(chart_path), use_container_width=True)
        st.caption(
            "Generated by scripts/backtest_cycle_phase.py — Core-tier only (no lookahead). "
            "Colors match the phase badges above."
        )
    else:
        st.warning("No backtest chart found. Run: `python scripts/backtest_cycle_phase.py`")

    history_csv = _OUTPUT_DIR / "cycle_backtest_history.csv"
    if history_csv.exists():
        hist = pd.read_csv(history_csv)
        with st.expander(f"Raw backtest history ({len(hist)} evaluation points)"):
            st.dataframe(hist.tail(50), use_container_width=True)


def render_validation():
    st.subheader("Validation — Independent Precision/Recall Check")
    report_path = _OUTPUT_DIR / "validation_report.txt"
    if not report_path.exists():
        st.warning("No validation report found. Run: `python scripts/validate_cycle_classifier.py`")
        return

    report_text = report_path.read_text(encoding="utf-8")
    lines = [l for l in report_text.splitlines() if l.strip()]
    metrics = {}
    for line in lines:
        if ":" in line:
            k, v = line.split(":", 1)
            metrics[k.strip()] = v.strip()

    recall_line = next((l for l in lines if l.startswith("Recall")), None)
    lift = metrics.get("lift_over_random")

    if recall_line:
        st.metric("Recall @ lead window", recall_line.split(":", 1)[1].strip().split("(")[0].strip())
    if lift is not None:
        try:
            lift_val = float(lift)
        except ValueError:
            lift_val = None
        if lift_val is not None:
            if lift_val < 1.1:
                st.error(
                    f"**Lift over random base rate: {lift_val}x** — the transition_risk signal is "
                    "NOT showing meaningful advance-warning skill over its own unconditional firing "
                    "rate at this lead window. This is an honest negative finding, not hidden: the "
                    "Core-tier (2-signal) transition_risk needs more evidence — breadth, valuation "
                    "history — before it can be trusted as a leading indicator. Concurrent phase "
                    "classification (the backtest chart above) tracks price structure more convincingly "
                    "than transition_risk anticipates turns."
                )
            else:
                st.success(f"**Lift over random base rate: {lift_val}x** — meaningfully above chance.")

    with st.expander("Full validation report + methodology"):
        st.code(report_text, language="text")
        st.caption(
            "Independent turn labels use a separate local-extrema + minimum-retracement "
            "algorithm — deliberately NOT the classifier's own ZigZag — so the ground truth "
            "isn't produced by the thing being scored. See scripts/validate_cycle_classifier.py."
        )

    turns_csv = _OUTPUT_DIR / "independent_labeled_turns.csv"
    if turns_csv.exists():
        with st.expander("Independently-labeled major turns"):
            st.dataframe(pd.read_csv(turns_csv), use_container_width=True)


def main():
    render_header()
    st.divider()

    try:
        data = fetch_synthesis()
    except Exception as exc:
        st.error(f"Synthesis failed: {exc}")
        return

    if data.get("status") == "unavailable":
        st.error(data.get("error", "Synthesis unavailable."))
        return

    render_classification(data)
    st.divider()
    render_evidence(data)
    st.divider()

    tab1, tab2 = st.tabs(["Backtest", "Validation"])
    with tab1:
        render_backtest()
    with tab2:
        render_validation()


if __name__ == "__main__":
    main()
