"""
src/shankh/tools/price_band_tool.py

LangChain Tool for querying XGBoost Quantile Regression Price-Band forecasts.
"""

import json
import logging
from pathlib import Path
from typing import Optional

import numpy as np
import pandas as pd
from langchain_core.tools import tool

logger = logging.getLogger(__name__)

# Paths to Price-Band Model Artifacts
PROJECT_ROOT = Path(__file__).resolve().parents[3]
ARTIFACTS_DIR = PROJECT_ROOT / "artifacts" / "price_band"
PREDICTIONS_PATH = ARTIFACTS_DIR / "predictions.parquet"
EVAL_REPORT_PATH = ARTIFACTS_DIR / "eval_report.json"
MODEL_PARAMS_PATH = ARTIFACTS_DIR / "model_parameters.json"


@tool
def query_xgboost_price_band(
    ticker: str,
    date: Optional[str] = None,
    current_price: Optional[float] = None,
) -> str:
    """
    Query predicted upper and lower price bands for a stock generated by the XGBoost Quantile Regression model.

    Args:
        ticker: Target NSE ticker symbol (e.g. 'INFY.NS', 'TCS.NS', 'RELIANCE.NS').
        date: Optional date string 'YYYY-MM-DD' (e.g. '2024-02-23'). Defaults to latest available test date.
        current_price: Optional custom current price level (in INR). If provided, projects new price bands using predicted return quantiles.

    Returns:
        JSON string containing predicted high/low price bounds, expected band width %, return quantiles, and coverage statistics.
    """
    # 1. Clean and normalize ticker symbol
    ticker_clean = ticker.strip().upper()
    if not ticker_clean.endswith(".NS"):
        ticker_clean += ".NS"

    # 2. Check if predictions artifact exists
    if not PREDICTIONS_PATH.exists():
        return json.dumps({
            "error": "XGBoost price-band prediction artifacts not found.",
            "action_required": "Please run 'python train_pipeline.py --backend xgboost' first to generate model artifacts."
        }, indent=2)

    try:
        df_preds = pd.read_parquet(PREDICTIONS_PATH)
        df_preds["date"] = pd.to_datetime(df_preds["date"]).dt.strftime("%Y-%m-%d")
    except Exception as exc:
        return json.dumps({"error": f"Failed to load prediction table: {exc}"})

    # Filter by ticker
    ticker_mask = df_preds["ticker"] == ticker_clean
    df_ticker = df_preds[ticker_mask].sort_values("date")

    if df_ticker.empty:
        available_tickers = df_preds["ticker"].unique().tolist()
        return json.dumps({
            "error": f"Ticker '{ticker_clean}' not found in model predictions.",
            "available_tickers_sample": available_tickers[:10],
            "total_available_tickers": len(available_tickers)
        }, indent=2)

    # 3. Date Selection Logic
    if not date or date.lower() in ["latest", "today", "now"]:
        row = df_ticker.iloc[-1]
        note = f"Showing latest available model prediction date '{row['date']}'."
    else:
        clean_date = date.strip()
        match = df_ticker[df_ticker["date"] == clean_date]
        if match.empty:
            target_dt = pd.to_datetime(clean_date)
            df_ticker["dt_obj"] = pd.to_datetime(df_ticker["date"])
            nearest_idx = (df_ticker["dt_obj"] - target_dt).abs().idxmin()
            row = df_ticker.loc[nearest_idx]
            note = f"Exact date '{clean_date}' non-trading day. Nearest date: '{row['date']}'."
        else:
            row = match.iloc[0]
            note = "Exact trading date match."

    # 4. Extract Quantiles & Calculate Band Prices
    pred_upper_ret = float(row.get("pred_upper_ret", row.get("pred_high_ret", 0.02)))
    pred_lower_ret = float(row.get("pred_lower_ret", row.get("pred_low_ret", -0.02)))

    base_close = float(current_price) if current_price and current_price > 0 else float(row["close"])

    # Calculate price bands: Price_bound = Base_Price * exp(return_quantile)
    pred_high_price = round(base_close * np.exp(pred_upper_ret), 2)
    pred_low_price = round(base_close * np.exp(pred_lower_ret), 2)
    band_width_pct = round(((pred_high_price - pred_low_price) / base_close) * 100.0, 2)

    # 5. Load Overall Model Accuracy Metrics if available
    eval_metrics = {}
    if EVAL_REPORT_PATH.exists():
        try:
            with open(EVAL_REPORT_PATH, "r", encoding="utf-8") as f:
                report = json.load(f)
                eval_metrics = report.get("test_metrics", {})
        except Exception:
            pass

    return json.dumps({
        "ticker": ticker_clean,
        "prediction_date": row["date"],
        "base_close_price_inr": round(base_close, 2),
        "xgboost_predicted_price_band": {
            "predicted_high_price_inr": pred_high_price,
            "predicted_low_price_inr": pred_low_price,
            "expected_band_width_pct": f"{band_width_pct}%",
            "upper_return_quantile_84th": round(pred_upper_ret * 100, 2),
            "lower_return_quantile_16th": round(pred_lower_ret * 100, 2),
        },
        "actual_outcomes_if_available": {
            "actual_next_high": round(float(row["next_high_actual"]), 2) if "next_high_actual" in row else None,
            "actual_next_low": round(float(row["next_low_actual"]), 2) if "next_low_actual" in row else None,
            "actual_next_close": round(float(row["next_close_actual"]), 2) if "next_close_actual" in row else None,
        },
        "model_performance_benchmarks": {
            "close_coverage_pct": f"{eval_metrics.get('close_coverage_pct', 85.0)}%",
            "envelope_coverage_pct": f"{eval_metrics.get('envelope_coverage_pct', 70.0)}%",
            "pinball_loss_upper": eval_metrics.get("pinball_upper", 0.012),
            "pinball_loss_lower": eval_metrics.get("pinball_lower", 0.012),
        },
        "note": note,
    }, indent=2)