"""
Executive Integration Test Suite for the Macro Analyst Agent.

Executes real-world multi-dimensional macro analysis queries using `build_macro_agent`.
Evaluates agent reasoning, tool orchestration, numerical grounding, and executive
report formatting for Chief Investment Officers (CIO) and lead analysts.
"""
from dotenv import load_dotenv
load_dotenv
import os  # noqa: E402
import pytest  # noqa: E402
from shankh.agents.macro.macro_agent import build_macro_agent  # noqa: E402


@pytest.mark.integration
class TestMacroAgentExecutiveWorkflow:
    """End-to-end integration tests proving Macro Agent analytical capabilities."""

    @pytest.fixture(autouse=True)
    def check_api_keys(self):
        """Ensure OpenAI API Key is present for integration agent execution."""
        if not os.getenv("OPENAI_API_KEY"):
            pytest.skip("OPENAI_API_KEY environment variable not set. Skipping live agent test.")

    def test_executive_macro_synthesis_workflow(self):
        """
        Executes a complex, multi-factor macroeconomic synthesis request.

        Validates that the agent invokes macro tools, analyzes institutional flows,
        evaluates US-India yield differentials and commodity velocity, and outputs
        a structured executive macro brief.
        """
        agent = build_macro_agent()

        task_prompt = (
            "Provide an executive-level macroeconomic synthesis for Indian equities for our CIO investment committee. "
            "Your analysis must address four critical pillars:\n"
            "1. Institutional Liquidity: Analyze daily FII/DII cash net flows and institutional market bias.\n"
            "2. Fixed Income & Yield Differentials: Evaluate India 10Y G-Sec yield, US 10Y Treasury yield, "
            "and compute the US-India 10Y yield spread in basis points to assess capital flight risk.\n"
            "3. Commodity & Forex Velocity: Analyze 5-day and 20-day price trends for Brent Crude Oil ($/bbl) "
            "and USD/INR spot rate. Explain transmission impacts on domestic CPI inflation and corporate profit margins.\n"
            "4. Economic Calendar Risk: Summarize key upcoming domestic Indian events and high-impact US macro cues.\n\n"
            "Format the output as a formal 'Executive Macro Brief' with explicit section headers, bulleted risk factors, "
            "and a final 'Portfolio Risk Stance' (Risk-On, Risk-Off, or Neutral). Do not include stock recommendations."
        )

        response = agent.invoke({"messages": [("user", task_prompt)]})

        assert "messages" in response, "Agent response must contain messages list"
        messages = response["messages"]
        assert len(messages) >= 2, "Agent trajectory must contain system/user and AI messages"

        tool_calls_detected = False
        for msg in messages:
            if hasattr(msg, "tool_calls") and msg.tool_calls:
                tool_calls_detected = True
                break
            if getattr(msg, "type", "") == "tool":
                tool_calls_detected = True
                break

        assert tool_calls_detected, "Macro Agent must invoke underlying macro tools to answer prompt"

        final_message = messages[-1]
        final_text = getattr(final_message, "content", "")

        assert len(final_text) > 400, "Executive report output must be comprehensive (>400 chars)"

        keywords_to_verify = [
            "Executive",
            "FII",
            "DII",
            "Yield",
            "Brent",
            "USD/INR",
        ]
        for keyword in keywords_to_verify:
            assert (
                keyword.lower() in final_text.lower()
            ), f"Executive brief missing required macro dimension: '{keyword}'"

        assert (
            "buy" not in final_text.lower() or "not investment advice" in final_text.lower()
        ), "Output must maintain non-advisory research assistant boundaries"

        print("\n" + "=" * 80)
        print(" EXECUTIVE MACRO BRIEF GENERATED BY MACRO ANALYST AGENT")
        print("=" * 80)
        print(final_text)
        print("=" * 80)