"""
Executive Integration Test Suite for the Market Breadth Specialist Agent.

Executes real-world cross-sectional market participation requests using `build_breadth_agent`.
Evaluates tool orchestration over the 150-ticker universe, McClellan Oscillator interpretation,
sector matrix integration, and executive report formatting for portfolio managers.
"""

import os
import pytest
from shankh.agents.market.breadth_agent import build_breadth_agent


@pytest.mark.integration
class TestMarketBreadthAgentExecutiveWorkflow:
    """End-to-end integration tests proving Market Breadth Agent capabilities."""

    @pytest.fixture(autouse=True)
    def check_api_keys(self):
        """Ensure OpenAI API Key is configured for integration agent execution."""
        if not os.getenv("OPENAI_API_KEY"):
            pytest.skip("OPENAI_API_KEY environment variable not set. Skipping live agent test.")

    def test_executive_market_breadth_synthesis_workflow(self):
        """
        Executes a complex, multi-layered cross-sectional market breadth audit.

        Validates that the agent invokes `get_market_breadth_metrics` and
        `get_sector_participation_matrix`, evaluates moving average coverage across
        the 150-ticker universe, analyzes McClellan momentum, and outputs a structured
        Executive Market Breadth Brief.
        """
        agent = build_breadth_agent()

        complex_cro_prompt = (
            "Perform a rigorous, institutional-grade market breadth and participation audit "
            "across our 150-ticker Indian equity universe for the Investment Committee.\n\n"
            "Your report must explicitly analyze four critical participation pillars:\n"
            "1. Moving Average Participation: Evaluate the percentage of universe stocks trading "
            "above their 20-day, 50-day, and 200-day Simple Moving Averages. Identify whether short-term "
            "vs long-term trend divergence is present.\n"
            "2. Advance-Decline & McClellan Momentum: Analyze daily Advances vs Declines, the A/D ratio, "
            "and the McClellan Oscillator score. Explain whether buying or selling volume is driving the tape.\n"
            "3. 52-Week High/Low Expansion: Evaluate Net 52-Week Highs vs Lows. Determine if the market "
            "is experiencing broad expansion or narrow mega-cap concentration under the surface.\n"
            "4. Sector Leadership Matrix: Analyze sector positive participation rates and compare top leading "
            "vs lagging sector rotation dynamics.\n\n"
            "Format the output as a formal 'Executive Market Breadth Brief' using explicit section headers, "
            "a designated Breadth Regime classification, and a bulleted list of key breadth risk signals. "
            "Do not provide individual stock tips or trade recommendations."
        )

        response = agent.invoke({"messages": [("user", complex_cro_prompt)]})

        assert "messages" in response, "Agent response payload must contain messages list"
        messages = response["messages"]
        assert len(messages) >= 2, "Agent execution trajectory must contain system/user and AI messages"

        tool_calls_detected = False
        for msg in messages:
            if hasattr(msg, "tool_calls") and msg.tool_calls:
                tool_calls_detected = True
                break
            if getattr(msg, "type", "") == "tool":
                tool_calls_detected = True
                break

        assert tool_calls_detected, "Breadth Agent must invoke underlying breadth tools to answer prompt"

        final_message = messages[-1]
        final_text = getattr(final_message, "content", "")

        assert len(final_text) > 400, "Executive breadth brief output must be comprehensive (>400 chars)"

        required_keywords = [
            "Executive",
            "Breadth",
            "DMA",
            "McClellan",
            "52-Week",
            "Sector",
        ]
        for keyword in required_keywords:
            assert (
                keyword.lower() in final_text.lower()
            ), f"Executive breadth report missing required section/metric: '{keyword}'"

        assert (
            "buy" not in final_text.lower() or "not investment advice" in final_text.lower()
        ), "Output must maintain non-advisory research assistant boundaries"

        print("\n" + "=" * 80)
        print(" EXECUTIVE MARKET BREADTH BRIEF GENERATED BY BREADTH ANALYST AGENT")
        print("=" * 80)
        print(final_text)
        print("=" * 80)