"""
Executive Integration Test Suite for the Market Cycle Specialist Agent.

Executes real-world market cycle valuation requests using `build_cycle_agent`.
Evaluates tool orchestration, Fed Model Equity Risk Premium analysis, credit cycle integration,
and executive report formatting for asset allocation committees.
"""

import os
import pytest
from shankh.agents.market.cycle_agent import build_cycle_agent


@pytest.mark.integration
class TestMarketCycleAgentExecutiveWorkflow:
    """End-to-end integration tests proving Market Cycle Agent capabilities."""

    @pytest.fixture(autouse=True)
    def check_api_keys(self):
        """Ensure OpenAI API Key is configured for integration agent execution."""
        if not os.getenv("OPENAI_API_KEY"):
            pytest.skip("OPENAI_API_KEY environment variable not set. Skipping live agent test.")

    def test_executive_market_cycle_synthesis_workflow(self):
        """
        Executes a complex, multi-factor market cycle audit.

        Validates that the agent invokes `get_market_cycle_metrics` and
        `get_liquidity_and_credit_cycle`, evaluates Nifty P/E percentiles,
        computes Equity Risk Premium spreads, and outputs a structured
        Executive Market Cycle Brief.
        """
        agent = build_cycle_agent()

        complex_cio_prompt = (
            "Perform an institutional market cycle and macro valuation audit for our "
            "Asset Allocation Committee.\n\n"
            "Your report must explicitly address four valuation and cycle pillars:\n"
            "1. Index Valuations: Evaluate Nifty 50 P/E ratio, P/B ratio, Dividend Yield, and "
            "determine where current multiples sit relative to 10-year historical percentiles.\n"
            "2. Equity Risk Premium (ERP): Compute Index Earnings Yield minus India 10Y G-Sec Yield. "
            "Explain whether equities offer sufficient risk premium relative to risk-free debt.\n"
            "3. Monetary & Credit Cycle: Analyze bank credit growth YoY %, M3 money supply growth, "
            "and RBI liquidity stance to assess credit expansion vs economic output.\n"
            "4. Global Rates Transmission: Evaluate US 10Y and 2Y Treasury yields, compute the 10Y-2Y "
            "slope, and explain global yield curve signals.\n\n"
            "Format the output as a formal 'Executive Market Cycle Brief' using explicit section headers, "
            "a designated Cycle Phase classification, and a bulleted list of strategic asset allocation risk signals. "
            "Do not provide individual stock tips or trade recommendations."
        )

        response = agent.invoke({"messages": [("user", complex_cio_prompt)]})

        assert "messages" in response, "Agent response payload must contain messages list"
        messages = response["messages"]
        assert len(messages) >= 2, "Agent trajectory must contain system/user and AI messages"

        tool_calls_detected = False
        for msg in messages:
            if hasattr(msg, "tool_calls") and msg.tool_calls:
                tool_calls_detected = True
                break
            if getattr(msg, "type", "") == "tool":
                tool_calls_detected = True
                break

        assert tool_calls_detected, "Cycle Agent must invoke underlying cycle tools to answer prompt"

        final_message = messages[-1]
        final_text = getattr(final_message, "content", "")

        assert len(final_text) > 400, "Executive cycle brief output must be comprehensive (>400 chars)"

        required_keywords = [
            "Executive",
            "Cycle",
            "P/E",
            "Equity Risk Premium",
            "Yield",
            "Credit",
        ]
        for keyword in required_keywords:
            assert (
                keyword.lower() in final_text.lower()
            ), f"Executive cycle report missing required section/metric: '{keyword}'"

        assert (
            "buy" not in final_text.lower() or "not investment advice" in final_text.lower()
        ), "Output must maintain non-advisory research assistant boundaries"

        print("\n" + "=" * 80)
        print(" EXECUTIVE MARKET CYCLE BRIEF GENERATED BY CYCLE ANALYST AGENT")
        print("=" * 80)
        print(final_text)
        print("=" * 80)